version: '3'

services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 5173:5173

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 8000:8000
    env_file: ./backend/.env
    environment:
      DB_URL: ${DB_URL}

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mytestdb:/data/db

volumes:
  mytestdb:
